### ISSUE TITLE
Segmentation fault with unioncom

### ISSUE THREAD

**Issue by sroyyors** [caokai1073/UnionCom#2]
hi,
I am trying to use this package with some scATAC and scRNAseq data but I am experiencing segfaults. I am not sure whether there is a problem with my installation. I used torch 1.7 and torch vision 0.8.2 which are higher than the versions mentioned in the user manual. 

I have tried to use a small dataset with 1000 cells and 1000 features for one dataset and 1000 cells and 400 features for another. But they are failing with a seg fault. Any ideas?

Also is there example inputs of real data i can use to see ?

**Comment by caokai1073** [comment]
Hi,

Thank you for your comments. Can you please tell me which version you are using? UnionCom is now version 0.2.2 on PYPI. 

I tested the version 0.2.2 with scGEM and scNMT data (which you can download in this repository) using torch 1.7.1 and torchvision 0.8.2, and find that UnionCom works well. I'm not sure what caused your seg fault. Could it be that your GPU does not have enough memory?

I attach the example for you. You can open with jupyter notebook. 

If you have any questions, please feel free to contact me.

[example.zip](https://github.com/caokai1073/UnionCom/files/5750060/example.zip)

**Comment by caokai1073** [comment]
> hi,
> I am trying to use this package with some scATAC and scRNAseq data but I am experiencing segfaults. I am not sure whether there is a problem with my installation. I used torch 1.7 and torch vision 0.8.2 which are higher than the versions mentioned in the user manual.
> 
> I have tried to use a small dataset with 1000 cells and 1000 features for one dataset and 1000 cells and 400 features for another. But they are failing with a seg fault. Any ideas?
> 
> Also is there example inputs of real data i can use to see ?

**Comment by sroyyors** [comment]
hi I don't think I have a GPU. I am running this on our Linux server. Could that be why? I did try the scGEM example and that crashes too. I did not see anywhere that I would need a GPU to run this code.

**Comment by caokai1073** [comment]
Hi,  later work such as SCOT (attached file) also compared with unioncom using CPU only and got a reasonable result. Can you provide more information about  the error ? (e.g., Traceback)  Or I can run it for you if you needed?

[SCOT.pdf](https://github.com/caokai1073/UnionCom/files/5753094/SCOT.pdf)

**Comment by sroyyors** [comment]
hi,
I was about to respond. It turns out I was able to make it run! I needed to install pytorch too.. in addition to torch and torch vision. It finishes (it still ends with a segmentation fault), but I get results out. thanks for your help.

**Comment by caokai1073** [comment]
That's great!
Please feel free to contact me if something else doesn't make sense.

**Comment by sroyyors** [comment]
certainly, thanks for the help!
